std = "lua52"
new_globals = {
	"__errorMessage", -- comes from basic-require.lua

	"debug.disableEventLog",
	"debug.disableTimerLog",

	"system.bindKeyboard",
	"system.bindMouse",
	"system.disableChatCommandDisplay",
	"system.exit",
	"system.giveEventGift",
	"system.loadFile",
	"system.loadPlayerData",
	"system.newTimer",
	"system.removeTimer",
	"system.saveFile",
	"system.savePlayerData",

	"tfm.enum.emote",
	"tfm.enum.ground",
	"tfm.enum.particle",
	"tfm.enum.shamanObject",
	["tfm.enum.emote"] = {other_fields = true},
	["tfm.enum.ground"] = {other_fields = true},
	["tfm.enum.particle"] = {other_fields = true},
	["tfm.enum.shamanObject"] = {other_fields = true},

	"tfm.exec.addConjuration",
	"tfm.exec.addImage",
	"tfm.exec.addJoint",
	"tfm.exec.addPhysicObject",
	"tfm.exec.addShamanObject",
	"tfm.exec.bindKeyboard",
	"tfm.exec.changePlayerSize",
	"tfm.exec.chatMessage",
	"tfm.exec.disableAfkDeath",
	"tfm.exec.disableAllShamanSkills",
	"tfm.exec.disableAutoNewGame",
	"tfm.exec.disableAutoScore",
	"tfm.exec.disableAutoShaman",
	"tfm.exec.disableAutoTimeLeft",
	"tfm.exec.disableDebugCommand",
	"tfm.exec.disableMinimalistMode",
	"tfm.exec.disableMortCommand",
	"tfm.exec.disablePhysicalConsumables",
	"tfm.exec.disablePrespawnPreview",
	"tfm.exec.disableWatchCommand",
	"tfm.exec.displayParticle",
	"tfm.exec.explosion",
	"tfm.exec.freezePlayer",
	"tfm.exec.giveCheese",
	"tfm.exec.giveConsumables",
	"tfm.exec.giveMeep",
	"tfm.exec.giveTransformations",
	"tfm.exec.killPlayer",
	"tfm.exec.linkMice",
	"tfm.exec.lowerSyncDelay",
	"tfm.exec.moveObject",
	"tfm.exec.movePlayer",
	"tfm.exec.newGame",
	"tfm.exec.playEmote",
	"tfm.exec.playerVictory",
	"tfm.exec.removeCheese",
	"tfm.exec.removeImage",
	"tfm.exec.removeJoint",
	"tfm.exec.removeObject",
	"tfm.exec.removePhysicObject",
	"tfm.exec.respawnPlayer",
	"tfm.exec.setAutoMapFlipMode",
	"tfm.exec.setGameTime",
	"tfm.exec.setNameColor",
	"tfm.exec.setPlayerScore",
	"tfm.exec.setRoomMaxPlayers",
	"tfm.exec.setRoomPassword",
	"tfm.exec.setShaman",
	"tfm.exec.setShamanMode",
	"tfm.exec.setUIMapName",
	"tfm.exec.setUIShamanName",
	"tfm.exec.setVampirePlayer",
	"tfm.exec.snow",

	"tfm.get.misc.apiVersion",
	"tfm.get.misc.transformiceVersion",

	"tfm.get.room.community",
	"tfm.get.room.currentMap",
	"tfm.get.room.maxPlayers",
	"tfm.get.room.mirroredMap",
	"tfm.get.room.name",
	"tfm.get.room.passwordProtected",
	"tfm.get.room.uniquePlayers",

	"tfm.get.room.objectList",
	"tfm.get.room.playerList",
	["tfm.get.room.objectList"] = {other_fields = true},
	["tfm.get.room.playerList"] = {other_fields = true},

	"tfm.get.room.xmlMapInfo.author",
	"tfm.get.room.xmlMapInfo.permCode",
	"tfm.get.room.xmlMapInfo.mapCode",
	"tfm.get.room.xmlMapInfo.xml"
}
not_globals = {
	"collectgarbage",
	"dofile",
	"load",
	"loadfile",
	-- "require", -- not included in tfm, but available in this code

	"debug.debug",
	"debug.getuservalue",
	"debug.gethook",
	"debug.getinfo",
	"debug.getlocal",
	"debug.getmetatable",
	"debug.getregistry",
	"debug.getupvalue",
	"debug.setuservalue",
	"debug.sethook",
	"debug.setlocal",
	"debug.setmetatable",
	"debug.setupvalue",
	"debug.upvalueid",
	"debug.upvaluejoin",

	"io",

	"os.clock",
	"os.execute",
	"os.exit",
	"os.getenv",
	"os.remove",
	"os.rename",
	"os.setlocale",
	"os.tmpname"
}